#!/usr/bin/python
import socket
import os
import signal
import Queue
import subprocess

meta = {
	'author':'Benjamin Donnelly',
	'ported_by':'Benjamin Donnelly',
	'version':'0.1.0',
	'phantom_safe':True,
	'info':"""Query to see if a file exists, return as inst_var"""
}


variables = {"file":["","yes","file to check"],"varname":["","yes","Var to write to.  Access with 'echo @var_name_here'"]}


class commands:
	def __init__(self):
		return

	@staticmethod
	def run(variables, q):

		varname = variables['varname'][0]
		filename = variables['file'][0]
	

		out = os.path.exists(filename)

		if len(varname) > 0:
			returnthis = "set %s %s" % (varname, out)
			q.put(returnthis)
		

