#!/usr/bin/env python


meta = {
	'author':'Benjamin Donnelly',
	'ported_by':'Benjamin Donnelly',
	'version':'0.1.0',
	'info':""" Inserts tracking bugs into docx files.  Very stealthy, very cool. """
}

variables = {"output":["output","yes","The basename for your output .docx"],"filename":["","yes","The path to the .docx file to modify"],"remote_address":["localhost","yes","the remote address to have the file call back to"]}

import sys
import os
import subprocess

rel = '<Relationship TargetMode="External" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Id="rId1337" Target='

drawing = """<w:drawing mc:Ignorable="w14 wp14">
	<wp:inline distT="0" distB="0" distL="0" distR="0">
		<wp:extent cx="1" cy="1"/>
		<wp:effectExtent l="0" t="0" r="0" b="0"/>
		<wp:docPr id="4" name="pengwings"/>
		<wp:cNvGraphicFramePr>
			<a:graphicFrameLocks xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" noChangeAspect="1"/>
		</wp:cNvGraphicFramePr>
		<a:graphic xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main">
			<a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture">
				<pic:pic xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture">
					<pic:nvPicPr>
						<pic:cNvPr id="0" name="cumberbatch"/>
						<pic:cNvPicPr/>
					</pic:nvPicPr>
					<pic:blipFill>
						<a:blip r:link="rId1337"/>
						<a:stretch>
							<a:fillRect/>
						</a:stretch>
					</pic:blipFill>
					<pic:spPr>
						<a:xfrm>
							<a:off x="0" y="0"/>
							<a:ext cx="1" cy="1"/>
						</a:xfrm>
						<a:prstGeom prst="rect">
							<a:avLst/>
						</a:prstGeom>
					</pic:spPr>
				</pic:pic>
			</a:graphicData>
		</a:graphic>
	</wp:inline>
</w:drawing>"""


remote = ""
finame = ""
output = ""

if main():
	#if len(sys.argv) - 3 != 0:
	#	print "Usage: %s <filename> <remote_address>" % sys.argv[0]
	#	exit(0)

	
	
	rel = rel + '"' + remote + '" />'

	print "You better have write permissions to this folder, otherwise this is going to fail silently."

	os.system("mkdir tmp")
	os.system("unzip %s -d tmp" % finame)
		
	document = open("tmp/word/document.xml", "r")
	document_data = document.read()
	document.close()

	temp = document_data.split("</w:body>")
	temp.append("</w:body>" + temp[1])
	temp[1] = drawing

	document_data = "".join(temp)
	
	document = open("tmp/word/document.xml","w")
	document.write(document_data)
	document.close()

	rels = open("tmp/word/_rels/document.xml.rels","r")
	rels_data = rels.read()
	rels.close()

	temp = rels_data.split("</Relationships>")
	temp.append(rel)
	temp.append("</Relationships>")
		
	rels_data = "".join(temp)

	rels = open("tmp/word/_rels/document.xml.rels","w")
	rels.write(rels_data)
	rels.close()
	
	cwd1 = os.getcwd() 
	cwd1 = cwd1 + "/tmp"
	print cwd1
	
	p = subprocess.Popen("zip -r %s.docx *" % (output), stdout=None, shell=True, cwd=cwd1)
	p.wait()

	os.system("mv tmp/%s.docx ./" % (output))
	os.system("rm -rf tmp")
	

class commands:
	def __init__(self):
		return
	
	@staticmethod
	def run(variables, pt):
		global remote
		global finame
		global output
		
		output = variables['output'][0]
		remote = variables['remote_address'][0]
		finame = variables['filename'][0]
		
